version: '2'

#NETWORKING#################################################################
# By default Compose will set up a private network for the cluster #########
# Each container will join the network and can be reached by other #########
# containers at a host-name identical to the containres name       #########
# It's necessary to keep the master container_name as 'master'     #########
############################################################################
 
services:
  master:
    build: .
    image: pavanpkulkarni/spark_image_2.0.1:first_image
    container_name: master
    ports:
      - "8080:8080"
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/master.conf"]
#---------------------------------------
  slave:
    image: pavanpkulkarni/spark_image_2.0.1:first_image
    depends_on:
      - master
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/slave.conf"]